# Generated by Django 5.0.1 on 2024-06-19 20:19

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import leads.models
import randomslugfield.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(max_length=150, null=True, unique=True, verbose_name='Адрес электронной почты')),
                ('photo', models.ImageField(blank=True, null=True, upload_to=leads.models.user_photo_path, verbose_name='Фото')),
                ('birthday', models.DateField(null=True, verbose_name='День рождения')),
                ('gender', models.CharField(choices=[('MALE', 'Мужчина'), ('FEMALE', 'Женщина'), ('OTHER', 'Другое')], max_length=150, null=True, verbose_name='Пол')),
                ('is_superuser', models.BooleanField(default=False, editable=False, verbose_name='Админ')),
                ('is_staff', models.BooleanField(default=False, editable=False, verbose_name='Сотрудник')),
                ('is_active', models.BooleanField(default=True, editable=False, verbose_name='Клиент')),
                ('url', randomslugfield.fields.RandomSlugField(blank=True, editable=False, length=15, max_length=15, null=True, unique=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Последняя изменения')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Создания')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Последняя изменения')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Создания')),
                ('user', models.OneToOneField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Профиль пользователя',
                'verbose_name_plural': 'Профили пользователя',
            },
        ),
    ]
